//! `docs/api/error-codes.md` is generated from the code, and this checks it still matches.
//!
//! Three SDKs — the C ABI, Swift, and React Native — tell developers to look up a code in that
//! table. A hand-maintained one drifts the first time somebody adds a variant and forgets, and
//! the failure is silent: the code is returned, the table does not list it, and the developer
//! concludes the library is undocumented.
//!
//! Same arrangement as the golden fixtures: `VDB_BLESS=1 cargo test -p vdb-core --test
//! error_codes_doc` regenerates, and CI fails if the committed file disagrees with the source.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use vdb_core::error::ALL_CODES;

fn doc_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/api/error-codes.md")
}

fn generate() -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- Generated by crates/vdb-core/tests/error_codes_doc.rs. Do not edit by hand: \
         run `VDB_BLESS=1 cargo test -p vdb-core --test error_codes_doc`. -->\n\n\
         # Error codes\n\n\
         Every failure the engine reports carries one of these. They are part of the public \
         contract and cross every language binding unchanged, so a caller can branch on a number \
         rather than matching on English.\n\n\
         Two rules govern them:\n\n\
         1. **Codes are append-only.** A released code keeps its meaning forever.\n\
         2. **Codes are never reused.** If a variant is removed its code is retired, not \
         recycled.\n\n\
         The band — the leading digit — is the contract for callers that do not recognise a \
         specific code. A client written against an older release can still tell storage trouble \
         from a validation mistake, which is what makes adding codes safe.\n\n",
    );

    let mut band = 0;
    for (code, name, description) in ALL_CODES {
        if code.band() != band {
            band = code.band();
            let _ = write!(
                out,
                "\n## {}xxx — {}\n\n| code | constant | meaning |\n|---|---|---|\n",
                band,
                code.band_name(),
            );
        }
        let _ = writeln!(out, "| `{}` | `{}` | {} |", code, name, description.trim(),);
    }

    let _ = write!(
        out,
        "\n## Reading a code\n\n\
         `{}` is the display form: the band, then the code. Bindings expose the number \
         itself — `error.code` in JavaScript and React Native, `code` on the Swift and Java error \
         types, `vdb_error_code()` in C.\n\n\
         The accompanying message is written for a developer and is not stable; do not match on \
         it. The code is.\n",
        vdb_core::error::ErrorCode::COLLECTION_NOT_FOUND,
    );
    out
}

#[test]
fn the_published_table_matches_the_code() {
    let generated = generate();
    let path = doc_path();

    if std::env::var("VDB_BLESS").is_ok() {
        if let Some(dir) = path.parent() {
            std::fs::create_dir_all(dir).expect("create docs/api");
        }
        std::fs::write(&path, &generated).expect("write the table");
        return;
    }

    let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing {}: {e}\nrun `VDB_BLESS=1 cargo test -p vdb-core --test error_codes_doc`",
            path.display()
        )
    });

    if committed == generated {
        return;
    }
    let first_diff = committed
        .lines()
        .zip(generated.lines())
        .position(|(a, b)| a != b)
        .unwrap_or(committed.lines().count().min(generated.lines().count()));
    panic!(
        "docs/api/error-codes.md is out of date with the code.\n  \
         first difference at line {}:\n    committed: {:?}\n    generated: {:?}\n  \
         Run `VDB_BLESS=1 cargo test -p vdb-core --test error_codes_doc` and commit the result.",
        first_diff + 1,
        committed.lines().nth(first_diff).unwrap_or("<end of file>"),
        generated.lines().nth(first_diff).unwrap_or("<end of file>"),
    );
}

/// Every code must carry a description, because the table is only useful if it explains itself.
#[test]
fn every_code_is_documented() {
    for (code, name, description) in ALL_CODES {
        assert!(
            description.trim().len() > 10,
            "{code} ({name}) has no useful description: {description:?}"
        );
    }
}

/// The band names must cover every band actually in use.
#[test]
fn every_band_in_use_has_a_name() {
    for (code, name, _) in ALL_CODES {
        assert_ne!(
            code.band_name(),
            "unassigned",
            "{code} ({name}) is in band {}, which has no name",
            code.band()
        );
    }
}
